version: '3.8'

volumes:
  postgres:
  pgadmin:

services:
  postgres:
    container_name: demo_postgres
    labels:
      org.springframework.boot.service-connection: postgres
    image: "postgres:15"
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "15432:5432"
    restart: unless-stopped
